name: NodejsCI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Scratch-CreadorCraft-Maker
        uses: ./
        with:
            path: './test'
            url: "https://raw.githubusercontent.com/Creadores-Program/Scratch-to-CreadorCraft-Maker-GHA/refs/heads/main/test/MinecraftTest.sb3"
