name: NodejsCI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v4
      - name: CreadorCraft-Maker
        uses: ./
        with:
            path: './test'
            url: "https://sheeptester.gitlab.io/test/special_cloud_behaviours_example.sb3"
